### PR TITLE
add noarch to build section

### PR DESCRIPTION
**Pull request by sannykr**

### CODE REVIEW

**Comment by jakirkham** [comment]
Needs a [re-render]( https://github.com/conda-forge/conda-smithy#re-rendering-an-existing-feedstock ) with `conda-smithy` 2.4.0 as well.

**Comment by sannykr** [comment]
@jakirkham : Can I rerender after merging?

**Comment by jakirkham** [comment]
No `noarch` won't work without a re-render. That said, this will actually remove all CIs except CircleCI, which is the fastest of the CIs. So should actually get results very quickly.

**Comment by sannykr** [comment]
@jakirkham : Thanks. I will make a new branch, rerender and then make a pull request with the required changes.

**Comment by jakirkham** [comment]
No worries. Went ahead and put up PR ( https://github.com/conda-forge/tox-feedstock/pull/4 ) to avoid further confusion. Hopefully that makes clear how this should be approached in the future. Please let me know if you have any questions.

**Comment by jakirkham** [comment]
This can be closed now that PR ( https://github.com/conda-forge/tox-feedstock/pull/4 ) is merged.

**Pull request closed without merging**
