### PR TITLE
Unping Pluggy from conda recipe to match pip

### LINKED ISSUE #95: Unping Pluggy from conda recipe to match pip
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

conda install of tox fails with the same list of versions when pip install succeeds. 

my particular issue was traced down to pluggy 
https://github.com/conda-forge/tox-feedstock/blob/main/recipe/meta.yaml
https://github.com/conda-forge/tox-feedstock/blob/a03bc496f8e47bbf2b6a3185a288d6b6fab29219/recipe/meta.yaml#L31
    - pluggy >=0.12.0,<1
https://github.com/tox-dev/tox/blob/00a969595d66c214467afc77cae26c6334f1ddbf/setup.cfg#L46
    pluggy>=0.12.0

There seem to be one additional inconsistencies between that conda yaml and setup.cfg 
    - importlib_metadata >=0.12,<2  # [py<38]
vs 
    importlib-metadata>=0.12;python_version<"3.8"

Workaround - Install tox using pip instead of conda - everything works, able to use in an environment where other packages are pinned to pluggy>1.0 

### Installed packages

```shell
_libgcc_mutex             0.1                 conda_forge    conda-forge
_openmp_mutex             4.5                       1_gnu    conda-forge
anyconfig                 0.10.1             pyhd8ed1ab_0    conda-forge
arrow                     1.2.2              pyhd8ed1ab_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
brotlipy                  0.7.0           py37h540881e_1004    conda-forge
bzip2                     1.0.8                h7f98852_4    conda-forge
c-ares                    1.18.1               h7f98852_0    conda-forge
ca-certificates           2021.10.8            ha878542_0    conda-forge
cachetools                4.2.4              pyhd8ed1ab_0    conda-forge
certifi                   2021.10.8        py37h89c1867_2    conda-forge
cffi                      1.15.0           py37h036bc23_0    conda-forge
chardet                   4.0.0            py37h89c1867_2    conda-forge
charset-normalizer        2.0.12             pyhd8ed1ab_0    conda-forge
click                     8.1.2            py37h89c1867_0    conda-forge
cookiecutter              1.7.3              pyh6c4a22f_1    conda-forge
cryptography              36.0.2           py37h38fbfac_0    conda-forge
curl                      7.82.0               h7bff187_0    conda-forge
distlib                   0.3.4                    pypi_0    pypi
dynaconf                  3.1.5              pyhd8ed1ab_0    conda-forge
expat                     2.4.8                h27087fc_0    conda-forge
filelock                  3.6.0                    pypi_0    pypi
fsspec                    2022.1.0           pyhd8ed1ab_0    conda-forge
gettext                   0.19.8.1          h73d1719_1008    conda-forge
git                       2.35.1          pl5321h36853c3_0    conda-forge
gitdb                     4.0.9              pyhd8ed1ab_0    conda-forge
gitpython                 3.1.27             pyhd8ed1ab_0    conda-forge
idna                      3.3                pyhd8ed1ab_0    conda-forge
importlib-metadata        4.11.3           py37h89c1867_1    conda-forge
importlib_metadata        4.11.3               hd8ed1ab_1    conda-forge
jinja2                    3.1.1              pyhd8ed1ab_0    conda-forge
jinja2-time               0.2.0              pyhd8ed1ab_3    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
jupyter_client            6.1.12             pyhd8ed1ab_0    conda-forge
jupyter_core              4.9.2            py37h89c1867_0    conda-forge
kedro                     0.18.0             pyhd8ed1ab_0    conda-forge
keyutils                  1.6.1                h166bdaf_0    conda-forge
krb5                      1.19.3               h3790be6_0    conda-forge
ld_impl_linux-64          2.36.1               hea4e1c9_2    conda-forge
libcurl                   7.82.0               h7bff187_0    conda-forge
libedit                   3.1.20191231         he28a2e2_2    conda-forge
libev                     4.33                 h516909a_1    conda-forge
libffi                    3.4.2                h7f98852_5    conda-forge
libgcc-ng                 11.2.0              h1d223b6_14    conda-forge
libgomp                   11.2.0              h1d223b6_14    conda-forge
libiconv                  1.16                 h516909a_0    conda-forge
libnghttp2                1.47.0               h727a467_0    conda-forge
libnsl                    2.0.0                h7f98852_0    conda-forge
libsodium                 1.0.18               h36c2ea0_1    conda-forge
libssh2                   1.10.0               ha56f1ee_2    conda-forge
libstdcxx-ng              11.2.0              he4da1e4_14    conda-forge
libzlib                   1.2.11            h166bdaf_1014    conda-forge
markupsafe                2.1.1            py37h540881e_1    conda-forge
ncurses                   6.3                  h9c3ff4c_0    conda-forge
openssl                   1.1.1n               h166bdaf_0    conda-forge
packaging                 21.3                     pypi_0    pypi
pcre2                     10.37                h032f7d1_0    conda-forge
pep517                    0.12.0           py37h89c1867_1    conda-forge
perl                      5.32.1          2_h7f98852_perl5    conda-forge
pip                       22.0.4             pyhd8ed1ab_0    conda-forge
pip-tools                 6.5.1              pyhd8ed1ab_0    conda-forge
platformdirs              2.5.1                    pypi_0    pypi
pluggy                    1.0.0            py37h89c1867_3    conda-forge
poyo                      0.5.0                      py_0    conda-forge
py                        1.11.0                   pypi_0    pypi
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pyopenssl                 22.0.0             pyhd8ed1ab_0    conda-forge
pyparsing                 3.0.7                    pypi_0    pypi
pysocks                   1.7.1            py37h89c1867_5    conda-forge
python                    3.7.12          hb7a2778_100_cpython    conda-forge
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python-json-logger        2.0.1              pyh9f0ad1d_0    conda-forge
python-slugify            6.1.1              pyhd8ed1ab_0    conda-forge
python_abi                3.7                     2_cp37m    conda-forge
pyyaml                    5.4.1            py37h5e8e339_1    conda-forge
pyzmq                     22.3.0           py37h336d617_1    conda-forge
readline                  8.1                  h46c0cb4_0    conda-forge
requests                  2.27.1             pyhd8ed1ab_0    conda-forge
rope                      0.21.1             pyhd8ed1ab_0    conda-forge
setuptools                61.3.0           py37h89c1867_0    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
smmap                     3.0.5              pyh44b312d_0    conda-forge
sqlite                    3.37.1               h4ff8645_0    conda-forge
text-unidecode            1.3                        py_0    conda-forge
tk                        8.6.12               h27826a3_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tomli                     2.0.1              pyhd8ed1ab_0    conda-forge
toposort                  1.7                pyhd8ed1ab_0    conda-forge
tornado                   6.1              py37h540881e_3    conda-forge
tox                       3.24.5                   pypi_0    pypi
tox-conda                 0.9.2                    pypi_0    pypi
traitlets                 5.1.1              pyhd8ed1ab_0    conda-forge
typing_extensions         4.1.1              pyha770c72_0    conda-forge
unidecode                 1.3.4              pyhd8ed1ab_0    conda-forge
urllib3                   1.26.9             pyhd8ed1ab_0    conda-forge
virtualenv                20.14.0                  pypi_0    pypi
wheel                     0.37.1             pyhd8ed1ab_0    conda-forge
xz                        5.2.5                h516909a_1    conda-forge
yaml                      0.2.5                h7f98852_2    conda-forge
zeromq                    4.3.4                h9c3ff4c_1    conda-forge
zipp                      3.7.0              pyhd8ed1ab_1    conda-forge
zlib                      1.2.11            h166bdaf_1014    conda-forge
```

### Environment info

```shell
WSL python=3.7
```

### PR DESCRIPTION
**Pull request by rxm7706**
Fixes https://github.com/conda-forge/tox-feedstock/issues/95

from
    - importlib_metadata >=0.12,<2  # [py<38]
to
    - importlib_metadata >=0.12,<5  # [py<38]
from
    - pluggy >=0.12.0,<1
to
    - pluggy >=0.12.0,<2

### CODE REVIEW

**Comment by bollwyvl** [comment]
@conda-forge-admin please rerender

**Comment by bollwyvl** [comment]
@rxm7706 thanks! i've pushed with fully re-synced and sorted versions: most had their upper bounds removed long ago, and us pinning tighter without reason doesn't help anybody very much.

i am semi-tempted to make this `noarch: python`... but we can evaluate that on a separate PR.

**Comment by bollwyvl** [comment]
Also, if you rely on getting `tox` from `conda-forge`, please consider adding yourself as a maintainer: I personally just need it as an upstream for testing other `conda-forge` feedstocks.

**Comment by rxm7706** [comment]
> @rxm7706 thanks! i've pushed with fully re-synced and sorted versions: most had their upper bounds removed long ago, and us pinning tighter without reason doesn't help anybody very much.
> 
> i am semi-tempted to make this `noarch: python`... but we can evaluate that on a separate PR.

Thanks - It hasn't shown up on conda-forge yet, so I am wondering what went wrong -- I see a message saying 
# Automatic uploading is disabled
also wondering if the build number should have been updated.
https://app.travis-ci.com/github/conda-forge/tox-feedstock/jobs/565660416#L988

**Comment by rxm7706** [comment]
> Also, if you rely on getting `tox` from `conda-forge`, please consider adding yourself as a maintainer: I personally just need it as an upstream for testing other `conda-forge` feedstocks.

@bollwyvl haven't really built a recipe before, learning the basics - this was easy to figure out, so figured I'd try and help

**Pull request merged**
